name: train_deploy_model_on_sagemaker
on:
  push:
    branches:
    - main
    - dev
    paths:
    - ".github/**"
    - "deploy/**"
    - "pipelines/**"
  workflow_dispatch:
jobs:
  publish_pipeline_and_train_model:
    name: Publish pipeline and train model
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Initialize Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.13
    - name: Install Python packages
      working-directory: ./pipelines
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Publish and trigger Sagemaker pipeline
      working-directory: ./pipelines
      run: |
        python run_pipeline.py \
          -n showcase.pipeline \
          -r ${SAGEMAKER_EXECUTIONROLE_ARN} \
          -k "{\"region\": \"eu-west-1\", \"role\": \"${SAGEMAKER_EXECUTIONROLE_ARN}\"}" \
          -t "[{\"Key\":\"createdBy\", \"Value\":\"github-actions\"}]"
      env:
        SAGEMAKER_EXECUTIONROLE_ARN: ${{ secrets.SAGEMAKER_EXECUTIONROLE_ARN }}

  deploy_endpoint:
    name: Deploy model to endpoint
    needs: publish_pipeline_and_train_model
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Initialize Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.13
    - name: Install Python packages
      working-directory: ./deploy
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Generate endpoint configuration files
      working-directory: ./deploy
      run: |
        python build_config_file.py \
          --model-package-group-name crayonShowcasePackageGroup \
          --model-execution-role ${SAGEMAKER_EXECUTIONROLE_ARN} \
          --datacapture-s3  ${SAGEMAKER_DEFAULT_S3_BUCKET}
      env:
        SAGEMAKER_DEFAULT_S3_BUCKET: ${{ secrets.SAGEMAKER_DEFAULT_S3_BUCKET }}
        SAGEMAKER_EXECUTIONROLE_ARN: ${{ secrets.SAGEMAKER_EXECUTIONROLE_ARN }}
    - name: Generate CloudFormation template
      working-directory: ./deploy
      run: |
        aws cloudformation package \
          --template endpoint-cloudformation.yml \
          --output-template cloudformation.yml \
          --s3-bucket ${SAGEMAKER_DEFAULT_S3_BUCKET}
      env:
        SAGEMAKER_DEFAULT_S3_BUCKET: ${{ secrets.SAGEMAKER_DEFAULT_S3_BUCKET }}
    - name: Deploy endpoint using CloudFormation template
      working-directory: ./deploy
      run: |
        aws cloudformation deploy \
        --template-file cloudformation.yml \
        --stack-name crayon-sagemaker-showcase \
        --parameter-overrides $(jq -r '.Parameters | to_entries[] | "\(.key)=\(.value)"' endpoint_config_adj.json)
